#!/bin/bash
set -e

echo "[Abyssal Installer] Installing dependencies..."
sudo apt-get update
sudo apt-get install -y tor proxychains macchanger lynis python3-pip
pip3 install --upgrade pip --break-system-packages
pip3 install --break-system-packages -r requirements.txt || true
echo "[Abyssal Installer] Done."
echo ""
echo "      _     _                 _       _ "
echo "     / \   | |__   ___   ___ | | __ _| |_ ___  _ __ "
echo "    / _ \  | '_ \ / _ \ / _ \| |/ _\\ | __/ _ \| '__|"
echo "   / ___ \ | | | | (_) | (_) | | (_| | || (_) | |   "
echo "  /_/   \_\|_| |_|\___/ \___/|_|\__,_|\__\___/|_|   "
echo "      🕶️  ABYSSAL  🐍"
echo ""
echo "    ___        _                 _     _ "
echo "   / _ \\__ _ | |__   ___   ___ | |__ (_)_ __   __ _ "
echo "  / /_)/ _\` || '_ \\ / _ \\ / _ \\| '_ \\| | '_ \\ / _\` |"
echo " / ___/ (_| || |_) | (_) | (_) | |_) | | | | | (_| |"
echo " \\/    \\__,_||_.__/ \\___/ \\___/|_.__/|_|_| |_|\\__, |"
echo "                                              |___/ "
echo "      🕶️  ABYSSAL  🐍"
echo ""
echo "  ___    ____  __   __  ____   ____   ___    _     _ "
echo " / _ \\  | __ ) \\ \\ / / | __ ) | __ ) / _ \\  | |   | |"
echo "| | | | |  _ \\  \\ V /  |  _ \\|  _ \\| | | | | |   | |"
echo "| |_| | | |_) |  | |   | |_) | |_) | |_| | | |___| |___"
echo " \\___/  |____/   |_|   |____/|____/ \\___/  |_____|_____|
echo "  █████╗ ██████╗ ██╗   ██╗███████╗███████╗███████╗ █████╗ ██╗     "
echo " ██╔══██╗██╔══██╗██║   ██║██╔════╝██╔════╝██╔════╝██╔══██╗██║     "
echo " ███████║██████╔╝██║   ██║█████╗  ███████╗█████╗  ███████║██║     "
echo " ██╔══██║██╔═══╝ ██║   ██║██╔══╝  ╚════██║██╔══╝  ██╔══██║██║     "
echo " ██║  ██║██║     ╚██████╔╝███████╗███████║███████╗██║  ██║███████╗"
echo " ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝"
echo "      🕶️  ABYSSAL  🐍"
echo ""
echo ""
echo "Usage:"
echo "  python3 abyssal.py --help         # Show help"
echo "  python3 abyssal.py --anon         # Start anonymity mode"
echo "  python3 abyssal.py --scan         # Run custom antivirus scan"
echo "  python3 abyssal.py --harden       # System hardening"
echo "  python3 abyssal.py --full         # Run all modules"
echo "  python3 abyssal.py --logkiller    # Erase system logs"
echo "  python3 abyssal.py --antimitm     # Run anti-MITM checks"
echo ""
echo "Run with sudo if required for system-level actions."
